name: NodeJS with Webpack

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Verify dist directory
        run: ls -la dist || echo "Dist directory not found"

      - name: Debug dist directory
        run: |
          echo "Contents of dist directory:"
          ls -la dist

      - name: Create .nojekyll file
        run: echo "" > dist/.nojekyll

      - name: Upload dist folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
